
GET http://localhost:8080/empleaos HTTP/1.1
Accept: application/json

GET http://localhost:8080/empleaos/6 HTTP/1.1
Accept: application/json

DELETE http://localhost:8080/empleaos/5 HTTP/1.1
Accept: application/json

PUT http://localhost:8080/empleao HTTP/1.1
Content-Type: application/json

{
    "id" : "8",
    "nombre" : "Marselo",
    "precio" : 34.2
}

POST http://localhost:8080/empleao HTTP/1.1
Content-Type: application/json

{
    "nombre" : "Marselo",
    "precio" : 3.3
}